twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ["form_bulma_theme.twig"]

    globals:
        dossier_images_annonces: "/build/images/"
